name: 🐞 Bug report
description: Report a reproducible problem in the project.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!

  - type: checkboxes
    id: no-duplicate
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this bug.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, I expect Y, but instead Z happens.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide steps so maintainers can reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, runtime, browser, app version, etc.
      placeholder: |
        - OS:
        - Runtime / Browser:
        - App version:
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Paste any relevant logs or add links to screenshots.
      render: shell
    validations:
      required: false
